version: "3.9"
services:
  backend:
    build:
      context: .
      target: exec
    image: inside:latest
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: inside
    ports:
      - 5432:5432
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d inside" ]
      interval: 1s
      timeout: 3s
      retries: 10
