openapi: 3.0.3
info:
  title: Moni
  description: "inside"
  version: 0.0.1
servers:
  - url: http://127.0.0.1:8080/api/v1
security:
  - CookieAuth: []

paths:
  /auth/signup:
    post:
      tags:
        - Authorization
      summary: Signup user
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupUserRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupUserResponse"

  /auth/login:
    post:
      tags:
        - Authorization
      summary: Login user
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginUserResponse"

  /auth/logout:
    delete:
      tags:
        - Authorization
      summary: Logout user
      security: []
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicResponse"

  /accounts/create:
    post:
      tags:
        - Accounts
      summary: Create an account
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccountRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccountResponse"
  /accounts/list:
    get:
      tags:
        - Accounts
      summary: List user accounts
      security: [ ]
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListUserAccountsResponse"
  /accounts/refill:
    post:
      tags:
        - Accounts
      summary: Deposit money to account
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefillAccountRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefillAccountResponse"
  /accounts/withdraw:
    post:
      tags:
        - Accounts
      summary: Withdraw money from account
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WithdrawFromAccountRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WithdrawFromAccountResponse"

  /accounts/buy:
    post:
      tags:
        - Accounts
      summary: (BUY) Transfer moeny from one account to another with currency conversion
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MakePurchaseRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MakePurchaseResponse"

  /accounts/sell:
    post:
      tags:
        - Accounts
      summary: (SELL) Transfer moeny from one account to another with currency conversion
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MakeSaleRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MakeSaleResponse"

  /currencies/list:
    get:
      tags:
        - Currencies
      summary: List currencies with some info
      parameters:
        - in: query
          name: code
          description: currency code
          schema:
            type: string
            enum: ["USD", "EUR", "RUB", "ILS", "INR", "JPY", "GBP", "KZT", "UAH", "EGP", "CNY"]
          required: true

      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCurrenciesResponse"

  /currencies/data:
    get:
      tags:
        - Currencies
      summary: Get currency price data for N days
      parameters:
        - in: query
          name: code
          description: currency code
          schema:
            type: string
            enum: ["USD", "EUR", "RUB", "ILS", "INR", "JPY", "GBP", "KZT", "UAH", "EGP", "CNY"]
          required: true
        - in: query
          name: ndays
          description: number of days
          schema:
            type: integer
            example: 1
          required: true
        - in: query
          name: base
          description: base currency
          schema:
            type: string
            enum: ["USD", "EUR", "RUB", "ILS", "INR", "JPY", "GBP", "KZT", "UAH", "EGP", "CNY"]
          required: true

      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCurrencyDataResponse"

  /admin/login:
    post:
      tags:
        - Admin
      summary: Login as Admin
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminLoginRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success

  /admin/update_user_status:
    put:
      tags:
        - Admin
      summary: Update User Status
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminUpdateUserStatusRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success

  /operations/list:
    post:
      tags:
        - Operations
      summary: List account operations
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ListOperationsRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOperationsResponse"

  /funtik/subscribe:
    post:
      tags:
        - Funtik
      summary: Trading bot by subsrcibtion
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscribeToFuntikRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscribeToFuntikResponse"
  /users/get:
    get:
      tags:
        - User
      summary: get user data
      security: [ ]
      responses:
        "500":
          description: Internal error
          content: { }
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  parameters:
    orderParam:
      in: query
      name: order
      schema:
        type: string
        enum: ["asc", "desc"]
    limitParam:
      in: query
      name: limit
      description: Pass '-1' integer to get all entries
      schema:
        type: integer
        minimum: 1
        default: 10
    sortByParam:
      in: query
      name: sort_by
      schema:
        type: string
        enum: ["created_at"]
    offsetParam:
      in: query
      name: offset
      schema:
        type: integer
        default: 0
    selectorParam:
      in: query
      name: selector
      description: A string to search for in all fields
      schema:
        type: string

  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: AuthToken

  schemas:
    SignupUserRequest:
      type: object
      properties:
        email:
          type: string
          example: mail@example.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        password:
          type: string
          example: password

    SignupUserResponse:
      $ref: "#/components/schemas/User"

    User:
      type: object
      properties:
        id:
          type: number
          example: 1
        email:
          type: string
          example: mail@example.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        password:
          type: string
          example: password
        mainAccountNumber:
          type: string

    LoginUserRequest:
      type: object
      properties:
        email:
          type: string
          example: mail@example.com
        password:
          type: string
          example: password

    LoginUserResponse:
      $ref: "#/components/schemas/User"

    CreateAccountRequest:
      type: object
      properties:
        currency:
          type: string
          example: RUB

    CreateAccountResponse:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/AccountItem'

    ListUserAccountsResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountItem'

    RefillAccountRequest:
      type: object
      properties:
        account_number:
          type: string
          example: a515a4bc-6805-11ed-9022-0242ac120002
        debit_amount_cents:
          type: integer
          example: 123

    RefillAccountResponse:
      type: object
      properties:
        account_number:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        old_balance:
          type: integer
          example: 1000
        new_balance:
          type: integer
          example: 1123
        purpose:
          type: string
          example: Пополнение счета с банковской карты

    WithdrawFromAccountRequest:
      type: object
      properties:
        account_number:
          type: string
          example: a515a4bc-6805-11ed-9022-0242ac120002
        credit_amount_cents:
          type: integer
          example: 123

    WithdrawFromAccountResponse:
      type: object
      properties:
        account_number:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        old_balance:
          type: integer
          example: 1000
        new_balance:
          type: integer
          example: 877
        purpose:
          type: string
          example: Вывод со счета на банковскую карту

    MakePurchaseRequest:
      type: object
      properties:
        account_number_from:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        currency_from:
          type: string
          example: "RUB"
        desired_amount_cents:
          type: integer
          example: 1000
        account_number_to:
          type: string
          example: c6f3c9e4-683f-11ed-9022-0242ac120002
        currency_to:
          type: string
          example: "USD"

    MakePurchaseResponse:
      type: object
      properties:
        old_account_from:
          $ref: '#/components/schemas/AccountItem'
        new_account_from:
          $ref: '#/components/schemas/AccountItem'
        old_account_to:
          $ref: '#/components/schemas/AccountItem'
        new_account_to:
          $ref: '#/components/schemas/AccountItem'
        purpose:
          type: string
          example: Перевод со счета c6f3c9e4-683f-11ed-9022-0242ac120002 (EUR) на счет fb33fd0e-6782-11ed-9022-0242ac120002 (RUB)

    MakeSaleRequest:
      type: object
      properties:
        account_number_from:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        currency_from:
          type: string
          example: "USD"
        selling_amount_cents:
          type: integer
          example: 100
        account_number_to:
          type: string
          example: c6f3c9e4-683f-11ed-9022-0242ac120002
        currency_to:
          type: string
          example: "RUB"

    MakeSaleResponse:
      type: object
      properties:
        old_account_from:
          $ref: '#/components/schemas/AccountItem'
        new_account_from:
          $ref: '#/components/schemas/AccountItem'
        old_account_to:
          $ref: '#/components/schemas/AccountItem'
        new_account_to:
          $ref: '#/components/schemas/AccountItem'
        purpose:
          type: string
          example: Перевод со счета c6f3c9e4-683f-11ed-9022-0242ac120002 (EUR) на счет fb33fd0e-6782-11ed-9022-0242ac120002 (RUB)

    ListCurrenciesResponse:
      type: object
      properties:
        currencies:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyItem'

    ListCurrencyDataResponse:
      type: object
      properties:
        code:
          type: string
          example: RUB
        price_data:
          type: array
          items:
            type: object
            properties:
              price:
                type: number
                example: 51.2
              date:
                type: string
                example: 2022-01-02

    ListOperationsRequest:
      type: object
      properties:
        account_numbers_in:
          type: array
          items:
            type: string
        operation_types_in:
          type: array
          items:
            type: string

    ListOperationsResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/OperationItem'

    SubscribeToFuntikRequest:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        account_number_from:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        subscribe_price_cents:
          type: integer
          example: 30000

    SubscribeToFuntikResponse:
      $ref: "#/components/schemas/BasicResponse"

    CurrencyItem:
      type: object
      properties:
        code:
          type: string
          example: USD
        name:
          type: string
          example: Доллар США
        current_price:
          type: number
          example: 62.5
        day_change_pct:
          type: number
          example: 1.04
        day_change:
          type: number
          example: -0.123
        month_change_pct:
          type: number
          example: -1.5
        month_change:
          type: number
          example: 2.1

    AccountItem:
      type: object
      properties:
        number:
          type: string
          example: fb33fd0e-6782-11ed-9022-0242ac120002
        user_id:
          type: string
          example: "1"
        currency:
          type: string
          example: RUB
        cents:
          type: string
          example: "10000"
        created_at:
          type: string
          example: 2006-1-2

    OperationItem:
      type: object
      properties:
        id:
          type: string
          example: 2bcc6904-6870-11ed-9022-0242ac120002
        purpose:
          type: string
          example: Вывод со счета на банковскую карту
        time:
          type: string
          example: 2022-11-20T01:28:59.586222Z
        operation_type:
          type: string
          example: withdrawal
        account_number_to:
          type: string
          example: 2bcc6904-6870-11ed-9022-0242ac120002
        amount_cents_to:
          type: number
          example: 1000.10
        currency_to:
          type: string
          example: RUB
        account_number_from:
          type: string
          example: 2bcc6904-6870-11ed-9022-0242ac120002
        amount_cents_from:
          type: number
          example: 100.01
        currency_from:
          type: string
          example: USD
        exchange_rate_ratio:
          type: number
          example: 10

    AdminLoginRequest:
      type: object
      properties:
        secret:
          type: string
          example: secret

    AdminUpdateUserStatusRequest:
      type: object
      properties:
        id:
          type: number
          example: 1
        status:
          type: string
          enum: [pending_approve, approved, banned]

    BasicResponse:
      type: object
